# This configuration is intended for development purpose
version : '3.8'
services :
  zookeeper :
    image : docker.io/bitnami/zookeeper:3.8
    container_name : quickstart-kafka-dev-stream-start-zookeeper
    restart : unless-stopped
    environment :
      ZOOKEEPER_CLIENT_PORT : 2181
      ZOOKEEPER_TICK_TIME : 2000
      ALLOW_ANONYMOUS_LOGIN : yes
  kafka :
    image : docker.io/bitnami/kafka:3.4
    container_name : quickstart-kafka-dev-stream-start-broker
    restart : unless-stopped
    depends_on :
      - zookeeper
    ports :
      - "9092:9092"
    environment :
      KAFKA_BROKER_ID : 1
      KAFKA_CFG_LISTENERS : PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS : PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT : zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER : yes

  prometheus :
    container_name : quickstart-kafka-dev-stream-start-prometheus
    image : prom/prometheus:v2.42.0
    volumes :
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : quickstart-kafka-dev-stream-start-grafana
    image : grafana/grafana:9.3.6
    volumes :
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
